---
# defaults file for storage-provider
artemis_uid: 1337
artemis_gid: 1337
artemis_user: artemis
artemis_group: artemis

# Storage server definition
storage_export:  /srv/artemis

# Storage Network 
storage_network: "fcfe:0:0:0:0:0:0:0/96"
storage_server_address: "fcfe:0:0:0:0:0:9:1"
