---

- name: Setup Artemis Load Balancer / Reverse Proxy
  hosts: artemis_cluster_proxy

  roles:
    - role: ls1intum.artemis.proxy
      vars:
        proxy_available_nodes:
          - hostname: "[fcfe::a:1]"
            weight: 1
          - hostname: "[fcfe::a:2]"
            weight: 1
          - hostname: "[fcfe::a:3]"
            weight: 1
