---
hermes_version:

hermes_apns_certificate_path:

hermes_apns_certificate_password:

hermes_apns_certificate_content:

hermes_apns_prod_environment:

hermes_google_application_credentials_json_path:

hermes_google_application_credentials_content:

hermes_working_directory:

hermes_port:

